apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-tea
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  hostGroup: "cafe"
  virtualServerAddress: "10.192.75.121"
  virtualServerHTTPSPort: 443
  tlsProfileName: reencrypt-cafe
  httpTraffic: redirect
  snat: auto
  pools:
  - monitor:
      interval: 10
      recv: ""
      send: "GET /tea HTTP/1.1\r\nHost: cafe.example.com\r\n"
      timeout: 31
      type: https
    path: /tea
    service: nginx-ingress
    servicePort: 443