apiVersion: v1
kind: ConfigMap
metadata:
  name: global-cm
  namespace: default
  labels:
    f5nr: "true"
data:
  extendedSpec: |
    extendedRouteSpec:
    - namespace: cafeone
      vserverAddr: 10.192.125.65
      vserverName: cafeone
      allowOverride: true
      policyCR: default/policy-cafe
    - namespace: cafetwo
      vserverAddr: 10.192.125.66
      vserverName: cafetwo
      allowOverride: true
      policyCR: default/policy-cafe